teiid:
  string:
    postgres:
      IsLengthFixed:
      dtype:
        true: CHAR
        false: VARCHAR
      max_length:
        4000: 65535
      length_columns:
        - Length
    mssql:
      IsLengthFixed:
      dtype:
          true: CHAR
          false: VARCHAR
      max_length:
        4000: MAX
      length_columns:
        - Length
  integer:
    postgres:
      dtype:
        INT
    mssql:
      dtype:
        INT
  biginteger:
    postgres:
      dtype:
        BIGINT
    mssql:
      dtype:
        BIGINT
  long:
    postgres:
      dtype:
        BIGINT
    mssql:
      dtype:
        BIGINT
  short:
    postgres:
      dtype:
        SMALLINT
    mssql:
      dtype:
        SMALLINT
  boolean:
    postgres:
      dtype:
        BOOLEAN
    mssql:
      dtype:
        BIT
  float:
    postgres:
      dtype:
        FLOAT8
    mssql:
      dtype:
        FLOAT
  double:
    postgres:
      dtype:
        FLOAT8
    mssql:
      dtype:
        FLOAT
  decimal:
    postgres:
      dtype:
        DECIMAL
      max_length:
        32767 : '38, 8'
      length_columns:
        - Precision
        - Scale
    mssql:
      dtype:
        NUMERIC
      max_length:
        32767 : '38, 8'
      length_columns:
        - Precision
        - Scale
  bigdecimal:
    postgres:
      dtype:
        DECIMAL
      max_length:
        32767 : '38, 8'
      length_columns:
        - Precision
        - Scale
    mssql:
      dtype:
        NUMERIC
      max_length:
        32767 : '38, 8'
      length_columns:
        - Precision
        - Scale
  timestamp:
    postgres:
      dtype:
        TIMESTAMP
    mssql:
      dtype:
        DATETIME2
  object:
    postgres:
      dtype:
        BYTEA
    mssql:
      dtype:
        VARBINARY
  xml:
    postgres:
      dtype:
        VARBINARY
    mssql:
      dtype:
        VARBINARY
postgres:
  16:
    postgres:
      dtype: BOOLEAN
    mssql:
      dtype: BIT
  20:
    postgres:
      dtype: BIGINT
    mssql:
      dtype: BIGINT
  21:
    postgres:
      dtype: SMALLINT
    mssql:
      dtype: SMALLINT
  23:
    postgres:
      dtype: INTEGER
    mssql:
      dtype: INT
  25:
    postgres:
      dtype: TEXT
    mssql:
      dtype: NVARCHAR(MAX)
  1043:
    postgres:
      dtype: VARCHAR
    mssql:
      dtype: NVARCHAR(MAX)
  1082:
    postgres:
      dtype: DATE
    mssql:
      dtype: DATE
  1083:
    postgres:
      dtype: TIME
    mssql:
      dtype: TIME
  1114:
    postgres:
      dtype: TIMESTAMP
    mssql:
      dtype: DATETIME2
  1184:
    postgres:
      dtype: TIMESTAMP WITH TZ
    mssql:
      dtype: DATETIME2
  1700:
    postgres:
      dtype: NUMERIC
    mssql:
      dtype: DECIMAL
  701:
    postgres:
      dtype: DOUBLE PRECISION
    mssql:
      dtype: FLOAT
  700:
    postgres:
      dtype: REAL
    mssql:
      dtype: FLOAT
  17:
    postgres:
      dtype: BYTEA
    mssql:
      dtype: IMAGE
  114:
    postgres:
      dtype: JSON
    mssql:
      dtype: TEXT
  2950:
    postgres:
      dtype: UUID
    mssql:
      dtype: UNIQUEIDENTIFIER
mssql:
  int:
    postgres:
      dtype:
        INTEGER
    mssql:
      dtype:
        INT
  str:
    postgres:
      dtype:
        TEXT
    mssql:
      dtype:
        NVARCHAR(MAX)
  float:
    postgres:
      dtype:
        DOUBLE PRECISION
    mssql:
      dtype:
        FLOAT
  bool:
    postgres:
      dtype:
        BOOLEAN
    mssql:
      dtype:
        BIT
  datetime:
    postgres:
      dtype:
        TIMESTAMP
    mssql:
      dtype:
        DATETIME2
  date:
    postgres:
      dtype:
        DATE
    mssql:
      dtype:
        DATE
mysql:
  253:  # VARCHAR, CHAR, ENUM, SET, JSON
    postgres:
      dtype: TEXT
    mssql:
      dtype: NVARCHAR(MAX)
  3:    # INT
    postgres:
      dtype: INTEGER
    mssql:
      dtype: INT
  1:    # TINYINT
    postgres:
      dtype: SMALLINT
    mssql:
      dtype: SMALLINT
  2:    # SMALLINT
    postgres:
      dtype: SMALLINT
    mssql:
      dtype: SMALLINT
  4:    # FLOAT
    postgres:
      dtype: DOUBLE PRECISION
    mssql:
      dtype: FLOAT
  5:    # DOUBLE
    postgres:
      dtype: DOUBLE PRECISION
    mssql:
      dtype: FLOAT
  8:    # BIGINT
    postgres:
      dtype: BIGINT
    mssql:
      dtype: BIGINT
  9:    # MEDIUMINT
    postgres:
      dtype: INTEGER
    mssql:
      dtype: INT
  10:   # DATE
    postgres:
      dtype: DATE
    mssql:
      dtype: DATE
  11:   # TIME
    postgres:
      dtype: TIME
    mssql:
      dtype: TIME
  12:   # DATETIME
    postgres:
      dtype: TIMESTAMP
    mssql:
      dtype: DATETIME2
  7:    # TIMESTAMP
    postgres:
      dtype: TIMESTAMP
    mssql:
      dtype: DATETIME2
  246:  # DECIMAL
    postgres:
      dtype: NUMERIC
    mssql:
      dtype: DECIMAL
  249:  # TINYBLOB, TINYTEXT
    postgres:
      dtype: TEXT
    mssql:
      dtype: NVARCHAR(MAX)
  250:  # MEDIUMBLOB, MEDIUMTEXT
    postgres:
      dtype: TEXT
    mssql:
      dtype: NVARCHAR(MAX)
  251:  # LONGBLOB, LONGTEXT
    postgres:
      dtype: TEXT
    mssql:
      dtype: NVARCHAR(MAX)
  252:  # BLOB, TEXT
    postgres:
      dtype: TEXT
    mssql:
      dtype: NVARCHAR(MAX)
  254:  # CHAR, BINARY
    postgres:
      dtype: TEXT
    mssql:
      dtype: NVARCHAR(MAX)
  16:   # BIT
    postgres:
      dtype: BOOLEAN
    mssql:
      dtype: BIT