INSERT INTO PGG_DW.CONTROLE.qt_cargos_orgao_classificacao (
  orgao_codigo_siorg
	, orgao_nome
	, orgao_natureza_juridica
	, orgao_classificacao
	, cargo_descricao
	, quantidade_cargos
	, data_snapshot
)
SELECT
	OP.ORG_PADR_CODIGO as orgao_codigo_siorg
	, OP.ORG_PADR_NOME as orgao_nome
	, NJ.ORGAO_NATUREZA_JURIDICA_DESCRICAO as orgao_natureza_juridica
	, C.ORGAO_CLASSIFICACAO as orgao_classificacao
	, S.CARGO_COMISS_SUBNIVEL_DESCRICAO as cargo_descricao
	, SUM(FT.VALOR) AS quantidade_cargos
	, GETDATE() as data_snapshot
FROM
	PGG_DW.DW_APF_FATOS.FT_INFORMACOES_SIAPE FT
	JOIN PGG_DW.DW_APF_SIORG.DM_CARGO_COMISSIONADO_SUBNIVEL S
		ON FT.CARGO_COMISS_SUBNIVEL_ID = S.CARGO_COMISS_SUBNIVEL_ID
	JOIN PGG_DW.DW_APF_GERAL.DM_ORGAO_UNIFICADO OU
		ON FT.ORGAO_UNIFICADO_ID = OU.ORGAO_UNIFICADO_ID
	JOIN PGG_DW.DW_APF_GERAL.DM_ORG_PADRONIZADO OP
		ON OU.ORG_PADR_ID = OP.ORG_PADR_ID
	JOIN PGG_DW.DW_APF_GERAL.DM_ORGAO_NATUREZA_JURIDICA NJ
		ON OP.ORG_PADR_ID_NATUREZA_JURIDICA = NJ.ORGAO_NATUREZA_JURIDICA_ID
	JOIN PGG_DW.DW_APF_GERAL.DM_ORGAO_CLASSIFICACAO C
		ON OP.ORGAO_CLASSIFICACAO_ID = C.ORGAO_CLASSIFICACAO_ID
WHERE
	INFORMACAO_TIPO_ID = 20001
GROUP BY
	OP.ORG_PADR_CODIGO
	, OP.ORG_PADR_NOME
	, NJ.ORGAO_NATUREZA_JURIDICA_DESCRICAO
	, C.ORGAO_CLASSIFICACAO
	, S.CARGO_COMISS_SUBNIVEL_DESCRICAO;
