SELECT COUNT(1)
FROM PGG_DW.CONTROLE.sensor_test;

--código definitivo
-- SELECT COUNT(1)
-- FROM PGG_DW.DW_APF_FATOS.FT_INFORMACOES_SIAPE
-- WHERE INFORMACAO_TIPO_ID = 20001 AND SUBSTRING(CONVERT(VARCHAR, TEMPO_DIA_ID), 1, 6) = {{ ds_nodash[:6]-1 }}
