WITH tbl_tempo_dia_id AS (
	SELECT DISTINCT TEMPO_DIA_ID
	FROM PGG_DW.DW_APF_FATOS_BKP.FT_INFORMACOES_SIAPE_BKP
	WHERE INFORMACAO_TIPO_ID = 20001
),
tbl_fato AS (
	SELECT
    INFORMACOES_ID
		, HARMONIZACAO_BASICA_ID
		, INFORMACAO_TIPO_ID
		, TEMPO_DIA_ID
		, ORGAO_UNIFICADO_ID
		, ORGAO_SUPERIOR_UNIFICADO_ID
		, VINCULO_SERV
		, COR_ORIGEM_ETNICA
		, REGIME_JURIDICO
		, SITUACAO_VINC_SERV
		, IDADE
		, FAIXA_ETARIA4
		, ABONO_PERMANENCIA_ID
		, ESCOLARIDADE
		, SEXO
		, CARGO_EFT_NIVEL
		, MUNICIPIO_ID
		, CARGO_COMISS_SUBNIVEL_ID
		, PESSOA_TIPO_VINCULO_ID
		, VALOR
		, N5_ID_UNIDADE_ORGANIZACIONAL
		, DENOMINACAO_CARGO_ID
		, UORG_VINC
		, FT_INFORMACOES_SIAPE_DT_INCLUSAO
	FROM PGG_DW.DW_APF_FATOS.FT_INFORMACOES_SIAPE
	WHERE INFORMACAO_TIPO_ID = 20001 AND TEMPO_DIA_ID IN (SELECT TEMPO_DIA_ID FROM tbl_tempo_dia_id)),
tbl_fato_bkp AS (
	SELECT
    INFORMACOES_ID
		, HARMONIZACAO_BASICA_ID
		, INFORMACAO_TIPO_ID
		, TEMPO_DIA_ID
		, ORGAO_UNIFICADO_ID
		, ORGAO_SUPERIOR_UNIFICADO_ID
		, VINCULO_SERV
		, COR_ORIGEM_ETNICA
		, REGIME_JURIDICO
		, SITUACAO_VINC_SERV
		, IDADE
		, FAIXA_ETARIA4
		, ABONO_PERMANENCIA_ID
		, ESCOLARIDADE
		, SEXO
		, CARGO_EFT_NIVEL
		, MUNICIPIO_ID
		, CARGO_COMISS_SUBNIVEL_ID
		, PESSOA_TIPO_VINCULO_ID
		, VALOR
		, N5_ID_UNIDADE_ORGANIZACIONAL
		, DENOMINACAO_CARGO_ID
		, UORG_VINC
		, FT_INFORMACOES_SIAPE_DT_INCLUSAO
	FROM PGG_DW.DW_APF_FATOS_BKP.FT_INFORMACOES_SIAPE_BKP
	WHERE INFORMACAO_TIPO_ID = 20001 AND TEMPO_DIA_ID IN (SELECT TEMPO_DIA_ID FROM tbl_tempo_dia_id))
SELECT CASE
			WHEN COUNT(1) = 0
				THEN 1
			ELSE
				0
			END as qt_registros
FROM
	((SELECT *
	FROM tbl_fato)

	EXCEPT

	(SELECT *
	FROM tbl_fato_bkp)) T1
